# Schema: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
changelog:
  categories:
    - title: Dependency update
      labels:
        - "dependencies"

    - title: Changes
      labels:
        - "*"
